name: web-page
version: '0.1.0'
synopsis: a web-page type
description: See readme.md for verbage (if any)
maintainer: Tony Day <tonyday567@gmail.com>
license: MIT
license-file: LICENSE.md
bug-reports: https://github.com/tonyday567/web-page/issues
extra-source-files:
- stack.yaml
dependencies: []
library:
  source-dirs: src
  exposed-modules:
  - Web.Page
  - Web.Page.Bootstrap
  - Web.Page.Bridge
  - Web.Page.Css
  - Web.Page.Examples
  - Web.Page.Html
  - Web.Page.Html.Input
  - Web.Page.Js
  - Web.Page.Render
  - Web.Page.Rep
  - Web.Page.Rep.Input
  - Web.Page.Server
  - Web.Page.Types
  dependencies:
    - JuicyPixels
    - aeson
    - attoparsec
    - base
    - bifunctors
    - box
    - clay
    - colour
    - foldl
    - generic-lens
    - interpolatedstring-perl6
    - javascript-bridge
    - language-javascript
    - lens
    - lucid
    - lucid-svg
    - mmorph
    - mtl
    - protolude
    - scotty
    - streaming
    - text
    - transformers
    - unordered-containers
    - wai-middleware-static
tests:
  test:
    main: test.hs
    source-dirs:
    - test
    ghc-options:
    - -Wall
    - -O2
    - -threaded
    dependencies:
    - base
    - web-page
    - tasty
    - tasty-hspec
    - lens
    - lucid
    - protolude
    - text
executables:
  page-example:
    main: example.hs
    source-dirs: app
    ghc-options:
      - -funbox-strict-fields
      - -fforce-recomp
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - web-page
      - attoparsec
      - box
      - lens
      - lucid
      - protolude
      - scotty
      - text
      - wai
      - wai-extra
      - wai-middleware-static
      - optparse-generic
