name: web-page
version: '0.0.1.0'
synopsis: Haskell project web-page repo
description: <https://github.com/tonyday567/web-page>
maintainer: Tony Day <tonyday567@gmail.com>
license: MIT
license-file: LICENSE.md
bug-reports: https://github.com/tonyday567/web-page/issues
extra-source-files:
- README.md
dependencies:
- HTTP
- blaze-builder
- bytestring
- clay
- containers
- data-default
- happstack-server
- hjsmin
- jmacro
- language-javascript
- lens
- lucid
- mtl
- mvc-extended
- text
- transformers
- blaze-html
library:
  source-dirs: src
  exposed-modules:
  - Web.Page
  - Web.Page.Css
  - Web.Page.Js
  - Web.Page.Server
  - Web.Page.Html
  - Web.Page.Types
  - Web.Page.Render
  - Language.Javascript.JMacro.Chain
  dependencies:
  - base
tests:
  test:
    main: test.hs
    source-dirs:
    - src
    - test
    ghc-options:
    - -Wall
    - -O2
    - -threaded
    dependencies:
    - base >=4 && <5
    - web-page
    - hspec
    - tasty
    - tasty-hspec
    - http-client
    - pipes
    - pipes-http
    - pipes-bytestring
