name: web-page
version: '0.1.0'
synopsis: a web-page type
description: See readme.md for verbage (if any)
maintainer: Tony Day <tonyday567@gmail.com>
license: MIT
license-file: LICENSE.md
bug-reports: https://github.com/tonyday567/web-page/issues
extra-source-files:
- stack.yaml
dependencies:
  - aeson
  - attoparsec
  - base
  - bifunctors
  - box
  - bytestring
  - chart-svg
  - clay
  - containers
  - generic-lens
  - interpolatedstring-perl6
  - javascript-bridge
  - language-javascript
  - lens
  - lucid
  - lucid-svg
  - microlens
  - mmorph
  - mtl
  - protolude
  - scotty
  - text
  - wai
  - wai-extra
  - wai-middleware-static
  - stm
  - transformers
  - colour
  - streaming
  - unordered-containers
  - JuicyPixels
  - svg-tree
  - numhask-prelude
  - blaze-markup
  - suavemente
  - numhask-space
library:
  source-dirs: src
  exposed-modules:
  - Web.Page
  - Web.Page.Bootstrap
  - Web.Page.Bridge
  - Web.Page.Bridge.Rep
  - Web.Page.Chart
  - Web.Page.Css
  - Web.Page.Examples
  - Web.Page.Html
  - Web.Page.Html.Input
  - Web.Page.Js
  - Web.Page.Server
  - Web.Page.Types
  - Web.Page.Render
tests:
  test:
    main: test.hs
    source-dirs:
    - test
    ghc-options:
    - -Wall
    - -O2
    - -threaded
    dependencies:
    - web-page
    - tasty
    - tasty-hspec
executables:
  page-example:
    main: example.hs
    source-dirs: app
    ghc-options:
      - -funbox-strict-fields
      - -fforce-recomp
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - web-page
  chart-style:
    main: chart-style.hs
    source-dirs: app
    ghc-options:
      - -funbox-strict-fields
      - -fforce-recomp
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - web-page
