name: web-page
version: '0.0.2.0'
synopsis: a web-page type
description: See readme.md for verbage (if any)
maintainer: Tony Day <tonyday567@gmail.com>
license: MIT
license-file: LICENSE.md
bug-reports: https://github.com/tonyday567/web-page/issues
extra-source-files:
- readme.md
- stack.yaml
dependencies:
library:
  source-dirs: src
  exposed-modules:
  - Web.Page
  - Web.Page.Css
  - Web.Page.Js
  - Web.Page.Server
  - Web.Page.Html
  - Web.Page.Types
  - Web.Page.Render
  dependencies:
  - base
  - clay
  - data-default
  - etc
  - generic-lens-labels
  - happstack-server
  - language-javascript
  - lens
  - lucid
  - managed
  - protolude
  - text
tests:
  test:
    main: test.hs
    source-dirs:
    - test
    ghc-options:
    - -Wall
    - -O2
    - -threaded
    dependencies:
    - base >=4 && <5
    - bytestring
    - clay
    - data-default
    - etc
    - http-client
    - lens
    - lucid
    - managed
    - pipes
    - pipes-bytestring
    - pipes-http
    - protolude
    - tasty
    - tasty-hspec
    - text
    - web-page
