resolver: lts-13.21

packages:
- '.'

extra-deps:
  - git: https://github.com/ku-fpg/javascript-bridge.git
    commit: bb72dbb7d2f6376353f67aec6c251271ffb055d5
  - lucid-svg-0.7.1
  - box-0.0.1.1

allow-newer: true
