#nightly-2018-01-29

resolver: nightly-2019-03-22

packages:
- '.'
- '../box'

extra-deps:
  - generic-lens-1.1.0.0
  - git: https://github.com/ku-fpg/javascript-bridge.git
    commit: bb72dbb7d2f6376353f67aec6c251271ffb055d5
  - lucid-svg-0.7.0.0
