resolver: nightly-2018-01-27

packages:
- '.'

extra-deps:
  - git: https://github.com/tonyday567/mvc-extended.git
    commit: 3a9f7db2749d04795d773794b01714d63b35398b
  - mmorph-1.0.9
  - mvc-1.1.6
  - pipes-http-1.0.5
