resolver: lts-13.21

packages:
- '.'

extra-deps:
  # - generic-lens-1.1.0.0
  - git: https://github.com/ku-fpg/javascript-bridge.git
    commit: bb72dbb7d2f6376353f67aec6c251271ffb055d5
  - lucid-svg-0.7.1
  - box-0.0.1.1
  # - git: https://github.com/tonyday567/box.git
  #   commit: 542dec0c31060e4d12c5aa949ced8d5813827b7e

allow-newer: true
